### ISSUE TITLE
Excluded fields are not included in merged rehydrated state

### ISSUE THREAD

**Issue by dickerpulli** [larscom/ngrx-store-storagesync#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After rehydration of persisted feature state the state only holds the values that were not excluded in the `excludeKeys` config property.

## Expected behavior

After rehydration of persisted feature state the state should hold the values from localstorage, if they are not excluded. All other properties of the state (the excluded ones) should be filled with the initial state defined in the reducer.

## Minimal reproduction of the problem with instructions

- Create a state with two fields that have some concrete values in initial state, maybe
<pre><code>
interface State {
  a: boolean;
  b: boolean;
}
const initialState = {
  a = true;
  b = true;
}
</code></pre>
- Now make a configuration for ngrx-store-storagesync with `excludeKeys: ['b']`
- After rehydration field `a` is restored from localstorage and field `b` is not existing in the state.
- My expectation, after rehydration
<pre><code>
state = {
  a = &lt;rehydrated value&gt;;
  b = true; // from initialState
}
</code></pre>

## What is the motivation / use case for changing the behavior?

I want to have an initial state with some fields get restored from localstorage.

## Environment

<pre>
<code>
@ngrx/store version: 9.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
Electron
</code>
</pre>

**Comment by dickerpulli** [comment]
Problem was in missing initialState of featureState. No problem of your lib.

**Comment by dickerpulli** [comment]
I fixed it for me with adding a custom merge reducer, that merges the restored state and the initial state
<code>
export function reducer(state: State, action: Action): State {
    if (action.type === UPDATE) {
        return {
            ...initialState,
            ...state
        };
    }
    return featureReducer(state, action);
}
</code>

**Comment by larscom** [comment]
Hi, according to this unit test it should work as expected: 

https://github.com/larscom/ngrx-store-storagesync/blob/075beab8694e33a712013e43f09d5d16da3a9fa0/projects/ngrx-store-storagesync/test/storage-sync/storage-sync.spec.ts#L187
