### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by svbackend** [larscom/ngrx-store-storagesync#15]
### Hello, thanks for the package, I'm wondering is there any chance to make it work with Angular 10 + SSR? 

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

1. Issue with `ReferenceError: window is not defined`

2. Issue with FormSyncModule:

```
ERROR in node_modules/@larscom/ngrx-store-storagesync/lib/form-sync/form-sync.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@larscom/ngrx-store-storagesync) which declares FormSyncModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class **FormSyncModule** {
```

## Minimal reproduction of the problem with instructions

1. Install angular 10, ngrx-store 9.2.0 and andular universal 10
2. Install ngrx-store-storagesync 6.1.7
3. Try to open any page with SSR enabled

## What is the motivation / use case for changing the behavior?

Would be really cool to make it work with angular 10, if you can guide me what exactly causes this issue I could try to fix this and create a PR

## Environment

<pre>
<code>
@ngrx/store version: 9.2.0
@angular/*: 10.0.2
@nguniversal/express-engine: 10.0.0-rc.1
express: 4.15.2
</code>
</pre>

**Comment by larscom** [comment]
Hi,

The demo/showcase app implements the library as well and is using SSR with angular 10.
https://ngrx-store-storagesync.firebaseapp.com/

You need to setup build specifics to make it work. See:
https://github.com/larscom/ngrx-store-storagesync/blob/7373c4e9106ccbb2ea1b8dd98931610c98d73678/angular.json#L115

The universal server doesn't need the storage sync reducer.

**Comment by svbackend** [comment]
oh, ok, huge thanks!
