### ISSUE TITLE
ERROR in The target entry-point "@larscom/ngrx-store-storagesync" has missing dependencies

### ISSUE THREAD

**Issue by brianpooe** [larscom/ngrx-store-storagesync#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running ng serve throws error in the cli 

```javascript
ERROR in The target entry-point "@larscom/ngrx-store-storagesync" has missing dependencies:
 - lodash-es
```

## Expected behavior

To serve the app

## Minimal reproduction of the problem with instructions

update the angular project to version 10.0.14

## Environment

<pre>
<code>
"@angular/core": "~10.0.14",
@ngrx/store version: 10.0.0
 "typescript": "^3.9.6"

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code>
</pre>

**Comment by brianpooe** [comment]
Ohk solved it. I just npm installed lodash-es, seems like this is a new one after upgrading to v6.2.1. Just never had to before.

**Comment by larscom** [comment]
thanks for reporting, this shouldn't be happening. I've taken a look and should be fixed in next patch release.
