### ISSUE TITLE
JSON parse error when value is undefined

### ISSUE THREAD

**Issue by zack9433** [larscom/ngrx-store-storagesync#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

if localstorage exist a key which is undefined value, it can cause JSON parse error.

## Expected behavior

Prevent JSON to parse unefined string at rehydrating state.

## Environment

<pre>
<code>
@ngrx/store version: 8.1.0

Browser:
- [x] Chrome (desktop) version 75
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code>
</pre>

**Comment by larscom** [comment]
Hi,
Can you show your use case in which you set the state value to undefined?

**Comment by zack9433** [comment]
In my case, I have a key which has `undeined` value and it already sync to localstorage before login successfully. After login, response data will replace `undefined` value but if I don't click login button just reload page and will trigger rehydrate state and JSON parse error happened.

**Comment by larscom** [comment]
How does your state object look like where the undefined value live?

**Comment by larscom** [comment]
I've created a test for this:
https://github.com/larscom/ngrx-store-storagesync/blob/f2efde2a25ecd8f9d12757674547599dcc6c66e5/lib/test/rehydrate-state.spec.ts#L83

it seems to work fine

**Comment by zack9433** [comment]
I figure out the problem, I don't import feature state....😅

this is my initial state
```typescript
export interface AppState {
  router: fromRouter.RouterReducerState<RouterStateUrl>;
  isDarkTheme: boolean;
}
```

and these states which are I want to sync

```typescript
export function storageSyncReducer(reducer) {
  return storageSync<AppState>({
    features: [{ stateKey: 'isDarkTheme' }, { stateKey: 'auth' }], // auth is feature state
    storage: window.localStorage
  })(reducer);
}
```

After APP initialized, `auth` will automatically sync to localstorage by using `ngrx-store-storagesync` but the value is 'undefined' because I don't import feature state yet.

**Comment by larscom** [comment]
Ah, so everything works as expected now? :smiley:

**Comment by zack9433** [comment]
Yes, thx for your help.

**Comment by larscom** [comment]
Great, no problem.
