### ISSUE TITLE
angular 13 / ivy build

### ISSUE THREAD

**Issue by nicholas-ochoa** [larscom/ngrx-store-storagesync#25]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

ngrx-store-storagesync is compiled by ngcc compiler

## Expected behavior

ngrx-store-storagesync is distributed as an angular 13 / ivy native library

**Comment by larscom** [comment]
Version 13.0.0+ of @larscom/ngrx-store-storagesync is distributed with: "compilationMode": "partial" to support most versions of Angular.

See: https://www.npmjs.com/package/@larscom/ngrx-store-storagesync
