### ISSUE TITLE
JSON Reviver treats any text _containing_ date strings as dates

### ISSUE THREAD

**Issue by Xiphoseer** [larscom/ngrx-store-storagesync#42]
## Current Behavior

Currently, the logic in the reviver at 
https://github.com/larscom/ngrx-store-storagesync/blob/43f1469b9eedffbf0916014717e5f7d9f4e3135d/projects/ngrx-store-storagesync/src/lib/rehydrate-state.ts#L31
will consider a value to be a date, iff [`RegExp.prototype.test`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) returns true for the value for the regex 
https://github.com/larscom/ngrx-store-storagesync/blob/43f1469b9eedffbf0916014717e5f7d9f4e3135d/projects/ngrx-store-storagesync/src/lib/rehydrate-state.ts#L4

However, as can be seen in https://jsfiddle.net/dt07sv2h/8/, this will also return true for a string like
```json
{"date": "2023-01-01T01:00:00"}
```
which produces an "Invalid Date" object.

## Expected Behavior

Date string detection should at least use the RegExp `/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/` (note the `^` prefix), to detect dates.

While there is little reason to store non base64 encoded JSON in a string in an ngrx state, the current behavior is broken for all values that return "Invalid Date" with `new Date(value)` (or `Date.parse(value)`, so changing the behavior for those values should be backwards compatible. Consequently, another fix may be to also return `value` whenever `isNaN(Date.parse(value))` is true.

**Comment by larscom** [comment]
Thanks for reporting, is fixed in version **14.0.3** should be available in npmjs.
