### ISSUE TITLE
Angular Universal 

### ISSUE THREAD

**Issue by Horizont77** [larscom/ngrx-store-storagesync#45]
Hi,

i receive error "window is not defined", if i use to angular SSR.

are there any fix about this?

**Comment by larscom** [comment]
Hi, 

You can use build specific files, i've used Angular Universal in the past.

Checkout this part:
https://github.com/larscom/ngrx-store-storagesync/tree/v6.3.0/src/app/store/build-specifics

Best way is to checkout the project (git tag v6.3.0) and see how it's done ;-)
