### ISSUE TITLE
Prevent to show a warning message when ivy is enabled

### ISSUE THREAD

**Issue by zack9433** [larscom/ngrx-store-storagesync#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Enable Ivy and build project will show the following warning

```
WARNING in Entry point '@larscom/ngrx-store-storagesync' contains deep imports into '/Users/zackyang/work/tp-f2e/node_modules/lodash/merge', '/Users/zackyang/work/tp-f2e/node_modules/lodash/cloneDeep', '/Users/zackyang/work/tp-f2e/node_modules/lodash/isPlainObject'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

## Expected behavior

Prevent to show a warning message when ivy is enabled.
Perhaps to use `JSON.parse(JSON.stringify(obj))` to do deep copy object.

**Comment by larscom** [comment]
Will pick this up when Angular 9 releases as it is not an error. Thanks for reporting.
