### ISSUE TITLE
Using function to deserialize

### ISSUE THREAD

**Issue by hmendezm** [larscom/ngrx-store-storagesync#6]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X] Other... Please describe:
</code></pre>

## Current behavior

I would like to use a function to deserialize but I do not find the wayt to call it in the features.

```
export function jsonToUserState(state: Record<string, any>): IAppState {
  try {
    if (!(state.likePostIds instanceof Set)) {
      state.likePostIds = new Set(state.likePostIds);
    }
  } catch (_) {
    state.likePostIds = new Set([]);
  }
  return state as IAppState;
}
export function storageSyncReducer(reducer: ActionReducer<any>): ActionReducer<any> {
  return storageSync<IAppState>({
    features: [
      // saves the auth state to sessionStorage
      {
        stateKey: 'config',
        serialize: (featureState: Partial<IAppState>) => JSON.stringify(featureState),
        deserialize:jsonToUserState
      }
    ],
    storage: window.sessionStorage
  })(reducer);
}
```
## Expected behavior
Be able to to serialize and deserialize with functions.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem via
https://stackblitz.com or similar.

## Environment

<pre>
<code>
@ngrx/store version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code>
</pre>

**Comment by larscom** [comment]
Hi, 

Inside the function you get the state as string, not as  `Record<string, any>`

`function jsonToUserState(state: Record<string, any>)` is not right

you need: ==> `function jsonToUserState(state: string)`

`const parsedState = JSON.parse(state) as IAppState;`

now parsedState is of type IAppState;
