### ISSUE TITLE
Can not sync featurekey to localstorage

### ISSUE THREAD

**Issue by zack9433** [larscom/ngrx-store-storagesync#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Could not sync with the following situation at v6.0.0
```
// Store state
{
  "isDarkTheme": false,  // <- this key can not sync to localstorage
  "session": {
      ...
  }
}
```

## Expected behavior
v5.7.7 can deal with upon situation

## Environment

<pre>
<code>
@ngrx/store version: 8.6.0

Browser:
- [x] Chrome (desktop) version 79
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code>
</pre>

**Comment by larscom** [comment]
hi, thanks for reporting, is fixed in 6.0.1 :)
