### ISSUE TITLE
Manually store and rehydrate? 

### ISSUE THREAD

**Issue by tehZeno** [larscom/ngrx-store-storagesync#8]
## I'm submitting a...
[X] Feature request
[X] Documentation issue or request

## Current behavior

Framework automatically syncs to local storage and rehydrates on refresh (yes!) 

## Expected behavior

I'd like to be able to mutate my store without syncing to storage, then when the user abandons a certain flow I'd like to simply rehydrate from the last saved storage.

So basically wondering , is is possible to influence the store/rehydrate behaviour? can we turn off the auto syncing and trigger manually?

**Comment by larscom** [comment]
Hi,
Take a look at this test: https://github.com/larscom/ngrx-store-storagesync/blob/15dcbbd4d8691dc706c234eaa5a93d789aed307d/projects/ngrx-store-storagesync/test/state-sync.spec.ts#L118

I think this is what you need.

**Comment by tehZeno** [comment]
Hi Lars,

Thanks for the quick reply! 

I looked at this feature, it seems to bring to the table half of what I would like (if I understand it correctly). 

This makes it possible to easily skip syncing to the store when a flag is set to false. Which means I could easily do state mutations and only save when I toggle the flag. That's a good thing. 
Works perfectly well for my scenario of adding things.

When changing records however I can use the same behaviour (only save to local storage when shouldSync is set). But what if after mutating the store , and not wanting to save to storage, I want to rehydrate my store with the last stuff from local storage? 

e.g. lets say we are building an address book. 
- I edit the contact info for **Lars** in two screens
  - screen 1: set the name to **LarsCom** 
  - screen 2: set phonenumber to something
- Flag shouldSync = false, so no state saving is done to storage. Navigating between the two steps I want to see my current state (e.g. **LarsCom**) 
- I navigate with a cancel back to the main screen. This means I now do not want my current state anymore, but instead want to rehydrate from storage (**LarsCom** becomes **Lars** again). 

For the last step my guess is I'd want to manually trigger a rehydrate. Or I might be missing something entirely.

**Comment by larscom** [comment]
Anytime! 
As i see it, you need to keep track of 2 versions of contact info in the store. Something like a draft version and an active version or something. This also means that you need to keep track of the version that is currently in use.

Then when the cancel button is clicked, you switch to the version you need and visa versa.

**Comment by tehZeno** [comment]
Yep, that is how I started implementing it now ( create a copy as a draft, and edit that as a draft). 

But was figuring a manual rehydrate would override what I had in the store so that this wouldn't be an issue. Making my store as a whole sort of a draft, and doing the publish action to storage and vice versa.

**Comment by larscom** [comment]
all right, also, rehydration takes place at application startup/init only. 

Good luck!

**Comment by tehZeno** [comment]
Thanks. So the conclusion is that it is not currently possible to manually rehydrate. I'll continue with my current solution and might investigate this further in the future. 

Thanks for your time @larscom
